## Step 1. Problem Understanding

Brands need to select suitable influencers for different campaign goals such as awareness, sales potential, collaboration, and cost-efficient promotion.

## Step 2. Load Dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

pd.set_option("display.max_columns", 100)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

df_raw = pd.read_csv("../data/raw/new3.csv")

df_raw.head()

,ID,Name,Country,Collab Score,Broadcast Score,Commerce Score,Followers,Median Views,Engagement,Price,Field Tags,Video Tags
0,ongthibalong,Ông Thỉ Bà Long 🌚,Việt Nam,89.90,95.80,94.40,"1,1M","113,6K","9,03%",18.000.000 VND,"Tin tức và Giải trí, Làm đẹp và chăm sóc cá nh...",Tình yêu & Mối quan hệ lãng mạn
1,lucas_ke_chuyen,Lucas Kể Chuyện,Việt Nam,92.70,98.60,NaN,"784,8K","59,8K","40,46%",3.500.000 VND,NaN,Trò chơi điện tử
2,utthuyss,Út Thuý,Việt Nam,78.30,93.70,NaN,"1,2M","158,6K","15,68%",13.825.209 VND,NaN,Hát nhép
3,vtvcab.tintuc,VTVcab Tin tức,Việt Nam,NaN,NaN,NaN,"5,2M","312,3K","4,46%",20.238.000 VND,NaN,Tin tức xã hội & Sự kiện
4,ngkhangg.008,A ri é,Việt Nam,80.20,97.90,NaN,"1,5M","630,8K","20,53%",14.935.334 VND,NaN,"Tiểu phẩm, Hài kịch"

In [3]:
print("Rows:", df_raw.shape[0])
print("Columns:", df_raw.shape[1])

Rows: 2438
Columns: 12

## Step 3. Data Understanding

In [4]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2438 entries, 0 to 2437
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               2438 non-null   object
 1   Name             2436 non-null   object
 2   Country          2438 non-null   object
 3   Collab Score     2411 non-null   float64
 4   Broadcast Score  1780 non-null   float64
 5   Commerce Score   293 non-null    float64
 6   Followers        2438 non-null   object
 7   Median Views     2438 non-null   object
 8   Engagement       2438 non-null   object
 9   Price            2438 non-null   object
 10  Field Tags       1123 non-null   object
 11  Video Tags       2311 non-null   object
dtypes: float64(3), object(9)
memory usage: 228.7+ KB

In [5]:
df_raw.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,2438,1149,manhoangcao,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Name,2436,1155,Nhật Minh,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,2438,2,Việt Nam,2437,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Collab Score,"2,411.00",NaN,NaN,NaN,79.84,5.56,60.70,76.60,78.30,80.70,98.20
Broadcast Score,"1,780.00",NaN,NaN,NaN,94.35,2.61,90.10,92.30,94.40,96.50,100.00
Commerce Score,293.00,NaN,NaN,NaN,95.05,2.97,90.40,92.00,95.20,97.60,100.00
Followers,2438,898,"1,1M",147,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median Views,2438,1602,"1,1M",19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Engagement,2438,1038,"4,52%",12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price,2438,795,5.000.000 VND,112,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Field Tags,1123,243,Tin tức và Giải trí,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Video Tags,2311,622,Hài kịch,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
pd.DataFrame({
    "column": df_raw.columns,
    "dtype": df_raw.dtypes.astype(str),
    "missing_count": df_raw.isna().sum(),
    "missing_pct": (df_raw.isna().mean() * 100).round(2),
    "unique_values": df_raw.nunique()
})

,column,dtype,missing_count,missing_pct,unique_values
ID,ID,object,0,0.00,1149
Name,Name,object,2,0.08,1155
Country,Country,object,0,0.00,2
Collab Score,Collab Score,float64,27,1.11,251
Broadcast Score,Broadcast Score,float64,658,26.99,49
Commerce Score,Commerce Score,float64,2145,87.98,13
Followers,Followers,object,0,0.00,898
Median Views,Median Views,object,0,0.00,1602
Engagement,Engagement,object,0,0.00,1038
Price,Price,object,0,0.00,795
Field Tags,Field Tags,object,1315,53.94,243
Video Tags,Video Tags,object,127,5.21,622

## Step 4. Data Quality Check

In [7]:
total_rows = len(df_raw)
unique_ids = df_raw["ID"].nunique()
duplicate_rows = total_rows - unique_ids

print("Total rows:", total_rows)
print("Unique IDs:", unique_ids)
print("Duplicate rows:", duplicate_rows)
print("Duplicate %:", round(duplicate_rows / total_rows * 100, 2))

Total rows: 2438
Unique IDs: 1149
Duplicate rows: 1289
Duplicate %: 52.87

## Step 5. Clean Column Names

In [8]:
def clean_column_name(col):
    col = col.strip().lower()
    col = re.sub(r"[^a-z0-9]+", "_", col)
    col = re.sub(r"_+", "_", col).strip("_")
    return col

df = df_raw.copy()
df.columns = [clean_column_name(c) for c in df.columns]

df.head()

,id,name,country,collab_score,broadcast_score,commerce_score,followers,median_views,engagement,price,field_tags,video_tags
0,ongthibalong,Ông Thỉ Bà Long 🌚,Việt Nam,89.90,95.80,94.40,"1,1M","113,6K","9,03%",18.000.000 VND,"Tin tức và Giải trí, Làm đẹp và chăm sóc cá nh...",Tình yêu & Mối quan hệ lãng mạn
1,lucas_ke_chuyen,Lucas Kể Chuyện,Việt Nam,92.70,98.60,NaN,"784,8K","59,8K","40,46%",3.500.000 VND,NaN,Trò chơi điện tử
2,utthuyss,Út Thuý,Việt Nam,78.30,93.70,NaN,"1,2M","158,6K","15,68%",13.825.209 VND,NaN,Hát nhép
3,vtvcab.tintuc,VTVcab Tin tức,Việt Nam,NaN,NaN,NaN,"5,2M","312,3K","4,46%",20.238.000 VND,NaN,Tin tức xã hội & Sự kiện
4,ngkhangg.008,A ri é,Việt Nam,80.20,97.90,NaN,"1,5M","630,8K","20,53%",14.935.334 VND,NaN,"Tiểu phẩm, Hài kịch"

## Step 6. Convert Text to Number

In [9]:
def parse_compact_number(value):
    if pd.isna(value):
        return np.nan
    
    s = str(value).strip().upper()
    s = s.replace("\xa0", "").replace(" ", "")
    
    multiplier = 1
    
    if s.endswith("K"):
        multiplier = 1_000
        s = s[:-1]
    elif s.endswith("M"):
        multiplier = 1_000_000
        s = s[:-1]
    elif s.endswith("B"):
        multiplier = 1_000_000_000
        s = s[:-1]
    
    s = s.replace(",", ".")
    s = re.sub(r"[^0-9.\-]", "", s)
    
    try:
        return float(s) * multiplier
    except:
        return np.nan


def parse_percent(value):
    if pd.isna(value):
        return np.nan
    
    s = str(value).replace("%", "").replace(",", ".")
    s = re.sub(r"[^0-9.\-]", "", s)
    
    try:
        return float(s)
    except:
        return np.nan


def parse_price(value):
    if pd.isna(value):
        return np.nan
    
    s = str(value).upper().replace("VND", "")
    s = re.sub(r"[^0-9]", "", s)
    
    try:
        return float(s)
    except:
        return np.nan

In [10]:
df["followers_num"] = df["followers"].apply(parse_compact_number)
df["median_views_num"] = df["median_views"].apply(parse_compact_number)
df["engagement_pct"] = df["engagement"].apply(parse_percent)
df["price_num"] = df["price"].apply(parse_price)

for col in ["collab_score", "broadcast_score", "commerce_score"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

## Step 7. Handle Duplicate Influencers

In [11]:
def mode_or_first(series):
    s = series.dropna().astype(str)
    if s.empty:
        return np.nan
    return s.mode().iloc[0] if len(s.mode()) > 0 else s.iloc[0]


def combine_unique_text(series):
    values = []
    for item in series.dropna():
        parts = [x.strip() for x in str(item).split(",") if x.strip()]
        values.extend(parts)
    
    values = sorted(set(values))
    return ", ".join(values) if values else np.nan

In [12]:
agg_rules = {
    "name": mode_or_first,
    "country": mode_or_first,
    "collab_score": "median",
    "broadcast_score": "median",
    "commerce_score": "median",
    "followers_num": "median",
    "median_views_num": "median",
    "engagement_pct": "median",
    "price_num": "median",
    "field_tags": combine_unique_text,
    "video_tags": combine_unique_text
}

df_cleaned = (
    df.dropna(subset=["id"])
    .groupby("id", as_index=False)
    .agg(agg_rules)
)

print("Before:", df.shape)
print("After:", df_cleaned.shape)

Before: (2438, 16)
After: (1149, 12)

## Step 8. Feature Engineering

In [13]:
df_cleaned["cpv"] = (
    df_cleaned["price_num"] / df_cleaned["median_views_num"].replace(0, np.nan)
)

df_cleaned["view_rate_pct"] = (
    df_cleaned["median_views_num"] / df_cleaned["followers_num"].replace(0, np.nan) * 100
)

In [14]:
conditions = [
    df_cleaned["followers_num"] < 10_000,
    df_cleaned["followers_num"].between(10_000, 99_999),
    df_cleaned["followers_num"].between(100_000, 499_999),
    df_cleaned["followers_num"].between(500_000, 999_999),
    df_cleaned["followers_num"] >= 1_000_000
]

choices = ["Nano", "Micro", "Mid-tier", "Macro", "Mega"]

df_cleaned["creator_segment"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

#### Price tier:

In [15]:
price_conditions = [
    df_cleaned["price_num"].isna(),
    df_cleaned["price_num"] < 5_000_000,
    df_cleaned["price_num"].between(5_000_000, 14_999_999),
    df_cleaned["price_num"].between(15_000_000, 49_999_999),
    df_cleaned["price_num"] >= 50_000_000
]

price_choices = [
    "Unknown",
    "Low",
    "Medium",
    "High",
    "Premium"
]

df_cleaned["price_tier"] = np.select(
    price_conditions,
    price_choices,
    default="Unknown"
)

## Step 9. Create Potential Group

In [16]:
thresholds = {
    "broadcast_high": df_cleaned["broadcast_score"].quantile(0.75),
    "commerce_high": df_cleaned["commerce_score"].quantile(0.75),
    "collab_high": df_cleaned["collab_score"].quantile(0.75),
    "engagement_high": df_cleaned["engagement_pct"].quantile(0.75),
    "engagement_mid": df_cleaned["engagement_pct"].quantile(0.50),
    "views_high": df_cleaned["median_views_num"].quantile(0.75),
    "views_mid": df_cleaned["median_views_num"].quantile(0.50),
    "cpv_good": df_cleaned["cpv"].quantile(0.25),
    "cpv_mid": df_cleaned["cpv"].quantile(0.50),
    "cpv_high": df_cleaned["cpv"].quantile(0.75)
}

In [17]:
def classify_potential(row):
    has_commerce = pd.notna(row["commerce_score"])
    
    if (
        row["broadcast_score"] >= thresholds["broadcast_high"]
        and has_commerce
        and row["commerce_score"] >= thresholds["commerce_high"]
        and row["collab_score"] >= thresholds["collab_high"]
    ):
        return "All-round Potential"
    
    elif (
        has_commerce
        and row["commerce_score"] >= thresholds["commerce_high"]
        and row["engagement_pct"] >= thresholds["engagement_high"]
        and row["cpv"] <= thresholds["cpv_mid"]
    ):
        return "Sales Potential"
    
    elif (
        row["broadcast_score"] >= thresholds["broadcast_high"]
        and row["median_views_num"] >= thresholds["views_high"]
    ):
        return "Awareness Booster"
    
    elif (
        row["collab_score"] >= thresholds["collab_high"]
        and row["engagement_pct"] >= thresholds["engagement_mid"]
    ):
        return "Collab-ready"
    
    elif (
        row["cpv"] <= thresholds["cpv_good"]
        and row["median_views_num"] >= thresholds["views_mid"]
    ):
        return "Cost-efficient"
    
    elif (
        row["broadcast_score"] >= thresholds["broadcast_high"]
        and row["cpv"] >= thresholds["cpv_high"]
    ):
        return "High Reach - Low Efficiency"
    
    else:
        return "General / Low Priority"


df_cleaned["potential_group"] = df_cleaned.apply(classify_potential, axis=1)

## Step 10. Export Cleaned Dataset

In [18]:
df_cleaned.to_csv(
    "../data/cleaned/influencers_cleaned.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved cleaned dataset successfully.")
print(df_cleaned.shape)

Saved cleaned dataset successfully.
(1149, 17)